### ISSUE TITLE
seems not to work

### ISSUE THREAD

**Issue by colbrugit** [mkuron/mountclean-osx#1]
I don't know hoe to use makefile.

So I have installed by doing:

sudo cp mountclean.py /usr/local/bin
sudo chown root:wheel /usr/local/bin/mountclean.py
sudo chmod go-w /usr/local/bin/mountclean.py
sudo defaults write com.apple.loginwindow LogoutHook /usr/local/bin/mountclean.py
sudo cp de.uni-stuttgart.physcip.mountclean.plist /Library/LaunchDaemons
sudo launchctl load /Library/LaunchDaemons/de.uni-stuttgart.physcip.mountclean.plist

I log in as user A -> log out user A -> ssh with user B

Top is still showing processes owened by user A

mmhh seems not to work..... Can you help?

**Comment by mkuron** [comment]
I just uploaded a pre-built installer package to https://github.com/mkuron/mountclean-osx/releases/download/10/mountclean-10.dmg. Please try that.

You did not chmod the launchdaemon, so it might not have loaded.
Please note that processes are only killed if the home directory is still mounted in /home. The script does not currently care about user processes if the user does not have a mounted home directory.
